# Generated by Django 3.0.5 on 2020-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.PositiveIntegerField()),
                ('runningBalance', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('walletId', models.AutoField(primary_key=True, serialize=False)),
                ('currentbalance', models.PositiveIntegerField()),
            ],
        ),
    ]
