# Generated by Django 3.0.5 on 2020-05-06 18:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('WALLET_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CURRENT_BALANCE', models.PositiveIntegerField(default=0)),
                ('DATE_CREATED', models.DateTimeField(default=datetime.datetime(2020, 5, 6, 23, 46, 53, 260447))),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('TRANSACTION_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DATE_CREATED', models.DateTimeField(default=datetime.datetime(2020, 5, 6, 23, 46, 53, 262446))),
                ('AMOUNT', models.PositiveIntegerField()),
                ('RUNNING_BALANCE_SENDER', models.IntegerField(default=0)),
                ('RUNNING_BALANCE_RECEIVER', models.IntegerField(default=0)),
                ('WALLET_ID_RECEIVER', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_receiver', to='personal.Wallet')),
                ('WALLET_ID_SENDER', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_sender', to='personal.Wallet')),
            ],
            options={
                'verbose_name': 'Individual Transactions',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
