# Generated by Django 3.0.5 on 2020-04-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Individual Transactions', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='walletIdSender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='personal.Wallet'),
        ),
    ]
