# Generated by Django 3.0.5 on 2020-05-04 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200504_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='DATE_CREATED',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 23, 3, 12, 318638)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='DATE_CREATED',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 23, 3, 12, 317638)),
        ),
    ]
