# Generated by Django 3.0.5 on 2020-04-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_remove_transaction_walletidsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='walletIdSender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='personal.Wallet'),
        ),
    ]
