# Generated by Django 3.0.5 on 2020-04-30 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_transaction_walletidsender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='walletIdSender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_sender', to='personal.Wallet'),
        ),
    ]
