# Generated by Django 3.0.5 on 2020-04-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20200430_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='walletIdReceiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_receiver', to='personal.Wallet'),
        ),
    ]
