# Generated by Django 3.0.5 on 2020-05-05 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20200505_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='DATE_CREATED',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 21, 22, 1, 526050)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='DATE_CREATED',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 21, 22, 1, 526050)),
        ),
    ]
