# Generated by Django 3.0.5 on 2020-04-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_transaction_walletidreceiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='currentbalance',
            new_name='currentBalance',
        ),
    ]
