# Generated by Django 3.0.5 on 2020-05-06 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20200506_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='DATE_CREATED',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 17, 44, 3, 953984)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='DATE_CREATED',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 17, 44, 3, 952985)),
        ),
    ]
