# Generated by Django 3.0.5 on 2020-04-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20200430_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='AMOUNT',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='DATE',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='runningBalance',
            new_name='RUNNING_BALANCE',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionId',
            new_name='TRANSACTION_ID',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='walletIdReceiver',
            new_name='WALLET_ID_RECEIVER',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='walletIdSender',
            new_name='WALLET_ID_SENDER',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='currentBalance',
            new_name='CURRENT_BALANCE',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='walletId',
            new_name='WALLET_ID',
        ),
    ]
