# Generated by Django 3.0.5 on 2020-04-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20200430_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='WALLET_ID_SENDER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_sender', to='personal.Wallet'),
        ),
    ]
