# Generated by Django 3.0.5 on 2020-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_auto_20200430_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('USER_NAME', models.CharField(max_length=255)),
            ],
        ),
    ]
