# Generated by Django 3.0.5 on 2020-05-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
