# Generated by Django 3.0.5 on 2020-05-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_auto_20200503_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='RUNNING_BALANCE',
        ),
        migrations.AddField(
            model_name='transaction',
            name='RUNNING_BALANCE_RECEIVER',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='RUNNING_BALANCE_SENDER',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
