# Generated by Django 3.0.5 on 2020-05-03 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_auto_20200503_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='DATE',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
