# Generated by Django 3.0.5 on 2020-05-03 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0016_auto_20200503_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='DATE',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 51, 19, 613824)),
        ),
    ]
