# Generated by Django 3.0.5 on 2020-05-03 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_auto_20200503_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='DATE',
        ),
        migrations.AddField(
            model_name='transaction',
            name='DATE_CREATED',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 53, 8, 640533)),
        ),
        migrations.AddField(
            model_name='wallet',
            name='DATE_CREATED',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 14, 53, 8, 640533)),
        ),
    ]
